In [1]:
import numpy as np

In [2]:
np.aray([2,3,4])

AttributeError: module 'numpy' has no attribute 'aray'

In [3]:
np.array([2,4,3])

array([2, 4, 3])

In [4]:
np.array([9,8,7],[6,5,4],[3,2,1])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [5]:
np.array([[9,8,7],[6,5,4],[3,2,1]])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [6]:
#----or----------

In [7]:
list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [10]:
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [12]:
##->1,(1+5),(6+5),------     but it should be less than 46

In [13]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [14]:
# by default we will get the float form  

In [15]:
# to make it int check below

In [16]:
np.ones(6,int)

array([1, 1, 1, 1, 1, 1])

In [17]:
np.ones(int,6)

TypeError: expected a sequence of integers or a single integer, got '<class 'int'>'

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [20]:
np.ones(6,int,4)

TypeError: order must be str, not int

In [21]:
#### Create an array of zeros with 2 rows and 10 columns

In [22]:
np.zeros(2,10)

TypeError: Cannot interpret '10' as a data type

In [23]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [26]:
## In linespace we are distributing 1 int 4 equal parts 

In [27]:
np.linespace((0,1,4),int)

AttributeError: module 'numpy' has no attribute 'linespace'

In [28]:
np.linespace(0,20,8)

AttributeError: module 'numpy' has no attribute 'linespace'

In [29]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [30]:
np.linspace((0,20,8),int)

TypeError: unsupported operand type(s) for *: 'type' and 'float'

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.eye(5,int)

TypeError: 'type' object cannot be interpreted as an integer

In [33]:
np.linespace((0,20))

AttributeError: module 'numpy' has no attribute 'linespace'

In [34]:
np.linspace(0,20)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [35]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [36]:
## By default if we don't specify the limit it will automatically gives 50 equal part of 1

In [37]:
np.random.rand(3,2)

array([[0.44592019, 0.34150752],
       [0.7926277 , 0.33734276],
       [0.52073149, 0.50078664]])

In [38]:
## we will get uniform distribution of 3 rows 2 column bt it's value is less than 1 always

In [78]:
np.random.randn(3,2)

array([[-2.04920933,  1.13259761],
       [-1.31717008, -0.34273629],
       [-0.15534949,  1.63304356]])

In [74]:
## we will get normal distribution we will get both positive and negative number both

In [63]:
np.random.randint(1,2)

1

In [43]:
## In randint we get number ranging from 1 to 1 

In [44]:
np.random.randint(34,54)

37

In [45]:
## It will give the value integer ranging from 34 to 54 

In [46]:
np.random.randint(0,100,20)

array([67, 23, 35, 61,  4, 83, 82, 95, 80, 49,  3, 93, 55,  7, 67, 28, 92,
       99, 54, 31])

In [47]:
## we will get total 20-integer value which will range from 0-100

In [48]:
sample=np.arange(30)
sample.reshape(4,7)

ValueError: cannot reshape array of size 30 into shape (4,7)

In [49]:
## 4*7=28 so we can not distribute 30 numbers into 4 rows and 7 columns i.e we have to select such type of number 
## such that rows*column will give 30 like-5*6, 2*15, 30*1, 6*5 etc.  

In [50]:
sample.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
np.reshape(30,1)

array([30])

In [52]:
sample.min()

0

In [55]:
sample_rand=np.random.randint(0,100,20)

In [56]:
sample_rand

array([70, 40, 65, 80, 34, 71, 19, 14, 58, 11, 49, 65, 81, 29,  5, 28, 44,
       76, 32, 97])

In [57]:
sample_rand.min()

5

In [58]:
sample_rand.max()

97

In [59]:
sample_rand.argmin()

14

In [60]:
sample_rand.dtype()

TypeError: 'numpy.dtype[int32]' object is not callable

In [79]:
## rand.argmin will give the position of the min value of the array

In [80]:
sample_rand.dtype[]

SyntaxError: invalid syntax (2120609290.py, line 1)

In [81]:
sample_rand.dtype

dtype('int32')

In [82]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
## T stands for Transpose

In [89]:
a=np.random.rand(2,3)
a

array([[0.63628501, 0.76385194, 0.82961129],
       [0.30612622, 0.22407086, 0.9759246 ]])

In [90]:
a.T

array([[0.63628501, 0.30612622],
       [0.76385194, 0.22407086],
       [0.82961129, 0.9759246 ]])

In [91]:
sample_array=np.array(10,21)

TypeError: Cannot interpret '21' as a data type

In [92]:
sample_array=np.arrange(10,21)

AttributeError: module 'numpy' has no attribute 'arrange'

In [93]:
sample_array=np.arange(10,21)

In [94]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [95]:
sample_array[3:7]

array([13, 14, 15, 16])

In [96]:
## 3:7 will give all the element from the index 3 to 6 

In [97]:
sample_array[0:4]

array([10, 11, 12, 13])

In [98]:
sample_array[3:7]=100

In [99]:
sample_array

array([ 10,  11,  12, 100, 100, 100, 100,  17,  18,  19,  20])

In [100]:
sample_array[:]=21
sample_array

array([21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21])

In [101]:
## Two Dimensional Array

In [102]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [104]:
sample_matrix[0][2]

1

In [106]:
sample_matrix[1][3]

33

In [107]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [108]:
sample_matrix[:,:]

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [109]:
sample_matrix[:][:]

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [110]:
sample_matrix[2]

array([56, 76, 24,  7])

In [112]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [113]:
## (3,2) represent column that means firstly third column will get print after that second column 

In [114]:
sample_mtrix[:,(3,1)]

NameError: name 'sample_mtrix' is not defined

In [115]:
sample_matrix[:,(3,1)]

array([[23, 20],
       [33, 23],
       [ 7, 76]])

In [116]:
sample_matrix[2,1]

76

In [117]:
## ------------------------------Selection Techniques ----------------------------------------------------

In [118]:
sample_array=np.arange(10,21)

In [119]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [120]:
np.exp(sample_array)

array([2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [121]:
np.sqrt(sample_array)

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [122]:
np.log(sample_array)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227])

In [123]:
np.min(sample_array)

10

In [124]:
np.max(sample_array)

20

In [125]:
np.argmax(sample_array)

10

In [126]:
np.argmin(simple_array)

NameError: name 'simple_array' is not defined

In [128]:
np.argmin(sample_array)

0

In [129]:
np.square(sample_array)

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

In [130]:
np.std(sample_array)

3.1622776601683795

In [131]:
## std->standard deviation

In [132]:
np.var(sample_array)

10.0

In [133]:
## var->Variance

In [134]:
np.mean(sample_array)

15.0

In [135]:
array=np.random.randn(3,4)
array

array([[-0.74676646, -1.14740483, -1.3476729 ,  1.28557301],
       [ 0.84838172,  0.62079347,  0.23158559,  0.0921065 ],
       [ 1.08244938, -0.3186856 ,  0.54413506, -1.03665605]])

In [137]:
np.round(array,decimal=4)

TypeError: round_() got an unexpected keyword argument 'decimal'

In [138]:
np.round(array,decimals=4)

array([[-0.7468, -1.1474, -1.3477,  1.2856],
       [ 0.8484,  0.6208,  0.2316,  0.0921],
       [ 1.0824, -0.3187,  0.5441, -1.0367]])

In [139]:
## round(array,decimals=4) represent the round off the array element till 4 decimal 

In [140]:
np.round(array,decimals=10)

array([[-0.74676646, -1.14740483, -1.3476729 ,  1.28557301],
       [ 0.84838172,  0.62079347,  0.23158559,  0.0921065 ],
       [ 1.08244938, -0.3186856 ,  0.54413506, -1.03665605]])

In [141]:
sports=np.array(['golf','fball','cricket','fball','cricket'])
np.unique(sports)


array(['cricket', 'fball', 'golf'], dtype='<U7')

In [142]:
sports=np.array(['golf','fball','cricket','fball','cricket','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')

In [143]:
## U7, U10 etc represent word with largest character